name: Validate schemas

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-22.04

    steps:
      - name: install jsonschema
        run: pip install jsonschema

      - uses: actions/checkout@v2
        with:
          lfs: 'true'

      - name: Run schema validation
        run: ./validate.sh
